### ISSUE TITLE
Only part of the board is being drawn

### ISSUE THREAD

**Issue by lovelymono** [okonomichiyaki/josekle#31]
On Chromium, Linux with 2x display scaling, only part of the board is being drawn:

![](https://user-images.githubusercontent.com/99364286/167295179-5c6c4c6f-26b4-43e2-82a9-3653d5fa8eef.png)

I don't think it's supposed to be like this?

**Comment by yewang** [comment]
This is the intended behavior. The interface, by default, zooms in on the top-right corner, since most (but not necessarily all) joseki will reside within that region. The "+" and "-" buttons adjust the zoom level, and it is possible to zoom all the way out to see the full board, if you wish. The page remembers your preferred setting (per device via local storage).
